[tempo]
clock_format = "%I:%M %p"


[appearance]
font_name = "Jetbrains Mono"
scale_factor = 1.13
opacity = 0.7

[appearance.menu]
font_name = "Jetbrains Mono"
scale_factor = 1
opacity = 0.9




[appearance.background_color]
base = "#202020"
strong = "#000000"
weak = "#000000"
text = "#ffffff"


[appearance.secondary_color]
base = "#303030"
strong = "#000000"
weak = "#000000"
text = "#ffffff"

[appearance.primary_color]
base = "#00aa52"
strong = "#00c555"
weak = "#006c10"
text = "#ffffff"


[appearance.text_color]
base = "#ffffff"
strong = "#ffffff"
weak = "#ffffff"
text = "#ffffff"




